spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/eksworkdb?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&cacheDefaultTimezone=false'
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}