spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/eksworkdb?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&cacheDefaultTimezone=false'
    username: ${RDS_USER}
    password: ${RDS_PASSWORD}