spring:
  datasource:
    url: 'jdbc:mysql://eks-work-db.cxsisye60l2u.ap-northeast-2.rds.amazonaws.com:3306/eksworkdb?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&cacheDefaultTimezone=false'
    username: ${RDS_USER}
    password: ${RDS_PASSWORD}
