version: '3'
services:
  db:
    image: "mysql:8.0"
    container_name: "eks-prac-2024"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Seoul"
    platform: linux/x86_64